### ISSUE TITLE
Prototype interface

### ISSUE THREAD

**Issue by Nekitech** [tfcp68/battle-farm#2]
Create start interface in HTML

- own cards (maximum 15) face down
- own beds with plants (the same size as the maps) 3-5
- your gold and fertilizers
- portraits of rivals + their gold, fertilizers and number of cards
- gold is displayed as a progress bar or 212/250
- market (6 cards face up)
- deck + counter (1 card face down) 36 left

**Comment by octaharon** [comment]
```
- свои карты (максимум 15)  лицевой стороной
- свои грядки с растениями (того же размера что и карты) 3-5
- свое золото и удобрения
- портреты соперников + их золото, удобрения и кол-во карт
- золото отображается в виде прогресс бара либо 212/250
- рынок (6 карт лицом вверх)
- колода + счетчик (1 карта рубашкой вверх) 36 left

```

**Comment by Nekitech** [comment]
https://www.figma.com/file/fRR8njpwTle91RUpydj5b3/battle-farm?node-id=1%3A4&t=CK5ZJQBKmv7NOkgL-0
